language: go

install:
  - go get -v github.com/spf13/hugo
  - npm install -g bower
  - bower install
  - pip install --user awscli

script:
  - hugo version
  - make deploy

branches:
  only:
    - master

env:
  global:
  - secure: bsmUsydsF/cLuVFkRamGI7WpoCuK9zrXDSG55TYUvDuIKxx42DkwAmw9cLT7z7UpbaM9f3U+CXdUVB7wmVY1uLs0B2/ZHp8AUZYxZbTvfEQopw44WBjPZjrak4S7k5225dpInP5lKNZzll1xZHqnA11LUgpW2BWnPqj+xGCGhWqXdjlmfDUUYyMd981fmm3larFXQgNWFRbIExyPfdYVTzXc+gB5hoX8f6kn6FMR/4z/CKTRU/xk3LdN7VIoB8stRYkT9yn84ljo1CpTkzjBEvoV6t7ksRHGkDM62kwj6oAvyFhC5T6Kc4GfnemuVMKFkAPm1J1tjWjIeEi5WUcsx/zhQwkNDfaMNAi4o4ZNrZbww8Z8w9kOtt6/F5WSABhoTBIKhm8aPuya95Q5JghC4q77afGa6SHqkumq7e8WMcm2s0Vxwbo5HZoniTst+IdsXKjQgQuovtSUNeLI48ZFuaNpPbc+FUtd+AM6CFoA0YkbyooOVbIiw79Xk5sZQIAcWkvRSY+LitLt81KRsUQ233RWhcCX9u59WMP5+dJmFy6BxNmZKCrItfa7r9LDcyzYTllYNirj1YON9A7da9oHLc+pIHYB1u362C9Yhm5/fSTf6C4jswetHZ+yeqc5rXGgSDw0N2qUG9CO2pIzK3zvCfB+bqGkbY/lvpVyul5tT1g=
  - secure: iT4iGmlggrPOim6M5qnMbWDkeR8PRgzSRsHf2nEV/LceGUzbNxG6kyTFfqzNwBGa4/lleA+kfyiEcUmT3DIrrd8A7WWxiRRnjcdTTOih/2Q0c7yzqj1ZyOkP/Q6ARodu6QhkxERtLRQnA9AFVBSGaGQB8hxevctqcS/kcz0q4c8ElaewqwO+3Nt8Pxa4paPtDHGdzE5QdWe05/l3l+DWhNe0mXGOUKKm5V70giMqmNj/0hpv9vWPhA09WXzcMSugIUz+M7QNKtXdhs97b3fBQAigmLhZc+muqtHPX9Y2VMsVL+vc8T+qfYKAvLNMxTcq+5plphhVlFgxcZ5nj54p6Yv0PSx4xW/M3Dpya0i/Bj8p2NpSgKV9npfLkFwZPu9F5gANLvF9OkfuexZcMsByR4C3O3eFCizUZCnGS7uXPr9Ne/BLZo3oIMql/M05pmIN3mWpMO41qXPukXlW+WK+k2jW+QGX+Ypb1tVwp8BBRhe2ZrlntpBtxuWwdaEYohtLbVZt3BMwrepzb2FA6ZXe+H2UCdfFJGRNzGUjeaItE5A8qJ4bnPU+MLNmOWoWO5C13yUFeXlPeeOStP5ycFtDhw3cMbyoBwOFW+/jgs8/ih1p6JgS6SlLzGpFw7cZ1M1r9ixrKSLcJAbZivsPnz/sWiKviqeEEFNaprcAz+QTAy8=
