baseurl: "https://www.akinjide.me/"
languageCode: "en-us"
metaDataFormat: "yaml"
title: "Akinjide Bankole"
params:
  author: "Akinjide Bankole"
  description: "The personal website of Akinjide Bankole: programmer, speaker and designer."
  email: "r@akinjide.me"
  subtitle: "I'm just smart and I like to code."
  mailchimpFormAction: "https://akinjide.us13.list-manage.com/subscribe/post?u=145be832f9f3713fb2544aed2&amp;id=beb6406ab9"
  googleAnalyticsTrackingId: "UA-64387772-2"
  googleSiteVerification: "oJ8GUTtaWVuFvJXZ3L-MkR24avH0dMUNE8WsrtiS33w"
  navLinks:
    - title: "Twitter"
      url: "https://twitter.com/_akinjide"
    - title: "Facebook"
      url: "https://www.facebook.com/bakinjide"
    - title: "G+"
      url: "https://plus.google.com/+akinjidebankole"
    - title: "Github"
      url: "https://github.com/akinjide"
    - title: "Talks"
      url: "https://speakerdeck.com/akinjide"
    - title: "StackOverflow"
      url: "https://stackoverflow.com/users/6045122/akinjide"
    - title: "Email"
      url: "mailto:r@akinjide.me"
author:
  name: "Akinjide Bankole"
  email: "r@akinjide.me"
